; PlatformIO Project Configuration File
; 1 z 9 — Arduino Uno controller for LED panels + round 2 buttons

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    fastled/FastLED@^3.6.0
